### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by mateodelnorte** [timshadel/heroku-buildpack-github-netrc#14]
```
-----> github-netrc app detected
       Generated .netrc & .curlrc files (available only at build-time)
/app/tmp/buildpacks/eeb32e6e6d5d4de74da7a5db6b6ecd56d059db9e34b150f0574844b853937897162815fa2429ab515bbf53c66a754091f086ed265408cc53634a034363efe95e/lib/github.rb:20:in `[]': no implicit conversion of String into Integer (TypeError)
	from /app/tmp/buildpacks/eeb32e6e6d5d4de74da7a5db6b6ecd56d059db9e34b150f0574844b853937897162815fa2429ab515bbf53c66a754091f086ed265408cc53634a034363efe95e/lib/github.rb:20:in `block in github_user_orgs'
	from /app/tmp/buildpacks/eeb32e6e6d5d4de74da7a5db6b6ecd56d059db9e34b150f0574844b853937897162815fa2429ab515bbf53c66a754091f086ed265408cc53634a034363efe95e/lib/github.rb:20:in `each'
	from /app/tmp/buildpacks/eeb32e6e6d5d4de74da7a5db6b6ecd56d059db9e34b150f0574844b853937897162815fa2429ab515bbf53c66a754091f086ed265408cc53634a034363efe95e/lib/github.rb:20:in `map'
	from /app/tmp/buildpacks/eeb32e6e6d5d4de74da7a5db6b6ecd56d059db9e34b150f0574844b853937897162815fa2429ab515bbf53c66a754091f086ed265408cc53634a034363efe95e/lib/github.rb:20:in `github_user_orgs'
	from /app/tmp/buildpacks/eeb32e6e6d5d4de74da7a5db6b6ecd56d059db9e34b150f0574844b853937897162815fa2429ab515bbf53c66a754091f086ed265408cc53634a034363efe95e/lib/github.rb:26:in `user_block'
	from /app/tmp/buildpacks/eeb32e6e6d5d4de74da7a5db6b6ecd56d059db9e34b150f0574844b853937897162815fa2429ab515bbf53c66a754091f086ed265408cc53634a034363efe95e/bin/compile:54:in `<main>'
 !     Push rejected, failed to compile github-netrc app.
 !     Push failed
```

**Comment by alexanderGalushka** [comment]
same issue

**Comment by thure** [comment]
Same here :/

**Comment by danlutz** [comment]
Any updates here? Or did you guys find an alternative solution?

**Comment by CodingItWrong** [comment]
I ran into this error as well, and I was able to fix it by granting the following permissions to my auth token:

- All "repo" permissions
- "user > read:user" permission
